data:
  samples: 500

model:
  random_state: 42
  test_size: 0.2
  n_estimators: 100

mlflow:
  experiment_name: "Utilities_MLOps"
  model_name: "TransformerFailureModel"

api:
  host: "0.0.0.0"
  port: 8000

kafka:
  topic: "scada_stream"
  bootstrap_servers: "localhost:9092"

